import type { Metadata } from "next";
import { Funnel_Display } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import ThemeProvider from "@/components/ThemeProvider";

const funnelDisplaySans = Funnel_Display()
const funnelDisplayMono = Funnel_Display()

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${funnelDisplaySans.className} ${funnelDisplayMono.className} antialiased`}
      >
        <ThemeProvider>
          <ClerkProvider>
              {children}
          </ClerkProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
